README.md
debian/install
man6/cap32.6

Title says it all. I butchered the README.md and put most of it in a manpage.
We could go a step further by generating an html manpage from the groff manpage and referencing it directly in the README, but this would be a bit awkward.

Look Mom, we've got a manpage now !

---

cap32.cfg

Still more effort to document the emulator functionalities. What was not obvious I derived by looking at the code. It looks like at least two parameters are not used at all (scr_vsync and scr_led), but I might have missed something.

Commented out (most of) cap32.cfg file

---

doc/man.html
doc/man6/cap32.6
makefile
src/argparse.cpp
src/gui/src/CapriceAbout.cpp

- add --verbose option to control log verbosity from command line,
- now display compilation flags and git commit id from which the executable was compiled in the --version output.

Minor improvements to CL option parsing

---

doc/man.html
makefile

groff is more portable than man2html, and generates
nicer pages.

Use groff for HTML manual page generation

---

makefile

* Added WINE variable to be able to launch testrunner under native
MS Windows with 'make WINE= unit_test'
* Somehow symlinking seemed to fail if target was already present.
So debug build crashed if no make clean was done before.
Explicitly remove the symlink.

Native MS Windows makefile fix

---

src/cap32.cpp

Not pausing audio before pausing emulator created interesting stuttering sounds when pausing/iconifying the emulator when a sound was played. This fixes this.

Fixed audio pause

---

src/cap32.cpp
src/cap32.h

A funny bug in the offset computation made it so we were actually timed by the sound buffer. This patch fixes this - or so I hope :-)
See issue #72.

Timing fix

---

makefile
src/ipf.cpp

An attempt to address issue #11.
Tested partially under Windows 8 after compiling under MSYS2/Mingw64. No error seens at compilation or runtime, however I could not fully validate IPF loading since I do not have any IPF file to play with :-)

Preliminary IPF support under MS windows

---

makefile

To make the new shiny windows latest release usable out-of-the-box by our millions of users.

Added missing MSYS2 freetype dependencies

---

src/cap32.cpp

Partially addresses issue #74.
Sleep when we are paused or when we have nothing to do. To keep the UI responsive we sleep by slices of 1 ms.
The sync path when audio is enabled and we are sync'ed by it was not changed (need to fully understand the constraints here). So this patch is partial only, but it brings a nice CPU load improvement when audio is disabled or emulator is paused. No impact seen on the overall responsiveness (tried on a couple of games).

Limit CPU usage

---

src/gui/src/CapriceLoadSave.cpp
test/CapriceLoadSave.cpp

Disk images are often generated on Windows computers, and Windows
doesn't care about case sensitiveness, so you're as likely to end up
with BARBARIAN.DSK as barbarian.dsk. With this change, Caprice32 finds
the disk image in both cases.

Made extension matching in the load/save dialog case-insensitive.

---

src/gui/src/CapriceLoadSave.cpp
src/stringutils.cpp
src/stringutils.h

Disc collections from multiple sources rarely follow the same naming
pattern. This change makes it easier to find a disc whose case is
unknown, without having to potentially search two different places in
the list.
Also a bunch of indentation fixes, as it happens.

Made directory listings case-insensitive.

---

src/cap32.cpp
src/cap32.h
src/gui/src/CapriceLoadSave.cpp

Also made drive A disc the default when opening the dialog.
Plenty of games use several discs, and require flipping discs regularly
as the player moves around. Caprice32 remembering the last used path
means the player only has to open the dialog and select the new disc,
without having to navigate back to the game's directory each time.
Also sorry for the PR deluge. :) Just started using Caprice32, randomly fixing things as they come.

Remember paths when loading/saving a disc, snapshot, tape or cartridge.

---

cap32.cfg
src/cap32.cpp
test/integrated/dsk/test.sh

Fix #107 by counting emulated video frames instead of host (wall clock) time.
As an added bonus this allows to autocmd to work at high speed.
Added a one-frame delay between each key stroke else firmware debouncer eats duplicated letters. This could be optimized by adding a delay only on duplicated letters.
I've read that some user of other emulator use autotype on WinAPE for high volume entry like a complete BASIC program [(ref)](http://www.cpcwiki.eu/forum/applications/full-screen-basic-editor/msg153497/#msg153497). This direction make caprice32 a nice alternative to WinAPE (which is Windows-only).
If you accept this PR, please credit my real name (visible in git history).
Thank you for this nice emulator which code was clear enough to quickly offer this PR!

Fix autocmd high speed

---

src/cap32.cpp

* Wish to run unattended tests at maximum speed possible on host.
* UI menu includes a "Limit emulation speed" option that can be checked or not.
* "Limit emulation speed" is not read nor written in config: always set to `speed_limit=1` on emulator start.
* "Limit emulation speed" is read, obeyed and written in config.
* Alternative: command-line option, if config entry is not suitable.
Changing 3 lines is enough. Hence the PR.
Test case can do things like this:
sed -e "s|limit_speed=.*|limit_speed=1|" -e "s|printer=.*|printer=1|" <$(CDTC_ROOT)/tool/caprice32/cap32_local.cfg >cap32_forunittest.cfg
* Actual potential seem very low as default behavior is not changed.
Thank you for your attention.

Make "Limit emulation speed" persistent.

---

INSTALL.md
debian/patches/fix-install-path.patch

Some commits modified the cap32.cfg file, preventing one
debian specific patch to apply. Fixed this.
Also, slightly improved INSTALL.md formatting w.r.t debian.

Fixed debian packaging process

---

makefile
src/cap32.cpp
src/cap32.h
src/errors.h
src/ipf.cpp
src/slotshandler.cpp

Use dynamic loading for libcaps (both on windows and linux). Will allow caprice32 to launch even if libcaps shared lib is not installed on the system.
Will also ease packaging (no need to distribute libcaps along the binary package if we do not want to).

Dynamic ipf load

---

.travis.yml

Let's pull in the IPF library into Travis CI.
We download the x86_64 package, but since we only use the includes, we should be OK whatever the actul Travis build arch (which will very likely be x86_64 anyway).
Tested on Travis - seems to work just fine.

Added IPF support to Travis builds

---

INSTALL.md

I don't know if INSTALL.md is the right place, as this is very detailed.

Added detailed caprice32 build instructions for mingw64 on Windows 10.

---

src/asic.cpp
src/cap32.cpp
src/cap32.h
src/disk.h
src/fdc.cpp
src/gui/includes/CapriceLeavingWithoutSavingView.h
src/gui/includes/CapriceMenu.h
src/gui/includes/CapriceVKeyboardView.h
src/gui/src/CapriceLeavingWithoutSavingView.cpp
src/gui/src/CapriceMenu.cpp
src/gui/src/CapriceVKeyboardView.cpp
src/ipf.cpp
src/slotshandler.cpp

This verifies whether a change has been made to driveA or driveB (the
only slots in which we support saving for now) and warns if leaving
without having saved.
This solves #105

Implement a warning dialog when leaving without having saved changes

---

makefile

remove few spurious warnings at build time with unsupported gnu gcc flags.

clang build fix proposal.

---

src/slotshandler.cpp

Before the fix, .zip files containing .DSK could not be loaded,
as suffix '.DSK' was compared to '.dsk' resulting in the following error:
ERROR   src/slotshandler.cpp:1389 - File format unsupported for <file>.zip

Fix a bug on case-sensitve filesystems when loading .zip.

---

src/cap32.cpp
src/gui/src/CapriceMemoryTool.cpp

Graduate Software CPM+ Accessory ROMs don't use a standard CPC rom format and caprice was rejecting these.
This change extends the ROM loading code to validate these ROMs and load if it passes the checks. 
Reference: https://www.cpcwiki.eu/index.php/Graduate_Software

add support and validation for Graduate Software Accessory roms.

---

doc/man.html
doc/man6/cap32.6
src/argparse.cpp

The man page, the html manual and cap32 -h help files were all in need of updating.
The man page/html help file didn't have anything around the more recently added command line parameters.
cap32 -h needed updating to reflect that --inject took a filename, --offset took an address, and corrected an error in the example of --override (it used a lowercase o and should have been uppercase)

Update man page, html help and the -h section to update it all to current parameters
